### ISSUE TITLE
The resulting image is quite different from the example.

### ISSUE THREAD

**Issue by NAHOHYUN-SKKU** [xavihart/PDM-Pure#5]
I downloaded deepfloyd_if library as written link and ran FORCE_MEM_EFFICIENT_ATTN=1 python pdm_pure.py on the demo image without any modifications, but the result is quite different from the example. Are there any additional hyperparameters I should set?

![advdmpurified](https://github.com/user-attachments/assets/8f696bc9-bdec-42fc-a784-b77bafcf9951)
![mistpurified](https://github.com/user-attachments/assets/0bebabd1-a295-4dd3-a9da-5d60bec81128)
![glazepurified](https://github.com/user-attachments/assets/afc8565f-417d-42ca-a39e-537db2aa8b1e)
![sdspurified](https://github.com/user-attachments/assets/f02adc05-3977-4a4d-96a8-c7e421d4691a)

**Comment by xavihart** [comment]
I think you need to set resampler in line:20 to be smaller:

e.g. resampling = "10,0,0,0,0,0,0,0,0,0"

**Comment by xavihart** [comment]
here is the result when i set resampling to '10, 0, 0, 0, ....'
![image](https://github.com/user-attachments/assets/4c703e0a-51ce-49b6-a512-ef3a577375d1)

**Comment by NAHOHYUN-SKKU** [comment]
It works well. Thanks!
![purified](https://github.com/user-attachments/assets/71fc8407-2169-42c5-9099-bf1e52808758)
